### ISSUE TITLE
Fix name in package.json

### ISSUE THREAD

**Issue by kinow** [18F/accordion#7]
Hi, 

I'm not very familiar with Node.JS, so sorry if this is not an actual bug.

I'm trying to build 18F/glossary as I'm testing some glossary servers (but focused on SKOS), and I'm getting the following error there when running `npm install`.

```
npm http 200 https://registry.npmjs.org/mochify/-/mochify-2.17.0.tgz
npm ERR! Error: Invalid name: "@18f/accordion"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:310:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:234:40
npm ERR!     at fs.js:268:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-51-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/kinow/Development/js/workspace/glossary
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http 200 https://registry.npmjs.org/mocha
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/kinow/Development/js/workspace/glossary/npm-debug.log
npm ERR! not ok code 0
```

So I think accordion package name in package.json could be renamed as 18f/accordion, or maybe just accordion?

Thanks!
Bruno

Ubuntu 14.04.3 LTS
node v0.10.25
npm 1.3.10

Thanks
Bruno

**Comment by afeld** [comment]
Hmm, I just cloned the [glossary](https://github.com/18F/glossary) repository (as of https://github.com/18F/glossary/commit/0c06cf018516a1cfba9b8a6a1c27b2b711308074) and was able to run `npm install` successfully, and was able to do an `npm install glossary-panel` elsewhere...mind verifying you are still having the problem? Sorry for the slow response, btw!
